package controller;

public enum GeneralEvent implements IApplicationEvent {
	KNOWN_DEVICE_ADDED,
	KNOWN_DEVICE_REMOVED,
	KNOWN_DEVICE_ALLOWED,
	KNOWN_DEVICE_BLOCKED,
	
	DEVICE_DISCOVERED,
	DEVICE_CONNECTED,
	DEVICE_DISCONNECTED,
	
	SETTINGS_CHANGED,
	DISCOVER_DEVICES,
	SAVE_SETTINGS,
	
	ADD_ORDER,
	REMOVE_ORDER,
	WRITE_ORDERS;
}
