package controller;

public enum StatusEvent implements IApplicationEvent {
	KNOWN_CLIENT_ADDED,
	KNOWN_CLIENT_REMOVED,
	KNOWN_CLIENT_ALLOWED,
	KNOWN_CLIENT_BLOCKED,
	
	CLIENT_DISCOVERED,
	CLIENT_CONNECTED,
	CLIENT_DISCONNECTED,
	
	SETTINGS_CHANGED,
	
	ORDER_CONFIRM_MODEL_CHANGED;
}
